### ISSUE TITLE
Not actually an issue: just proud

### ISSUE THREAD

**Issue by fern-leigh-zz** [Jadelette/Katas#1]
Heeey!

So, I haven't done any tests for this yet, (as frankly I haven't the faintest idea how I'd have gone about writing them for this) - but I have written a programme to allow customers to add books to their basket, for the book-buying kata. I think it's pretty good, and I think it covers all possibilities - but I wondered if you'd take a look at a it and tell me if there's anything obviously wrong with it or that could have been done more easily/elegantly?

It's in Katas > src > Main > Potter 

I'll start working on the actual challenge form the kata using the basket list created by what I've done so far  - and I'll start using TDD now. :) 

Hope you're having a good weekend! I'm not expecting you to look at it today - just flagging for when you have time! :) 

J

**Comment by fern-leigh-zz** [comment]
package potter;

import java.util.ArrayList;
import java.util.Scanner;


public class Potter {


    public static void main(String[] args) {

        ArrayList<String> basket = new ArrayList<String>();

        boolean running = true;

        while (running == true) {

            System.out.println("Would you like to add a book to your basket? (yes/no)");
            Scanner scanner = new Scanner(System.in);

            if(scanner.hasNext()) {
                String yesNo = scanner.next();
                System.out.println(yesNo);

                switch (yesNo) {
                    case "yes":
                        System.out.println("which volume would you like to add?");
                        Scanner scanner2 = new Scanner(System.in);
                        if (scanner2.hasNextInt()) {
                            int volume = scanner2.nextInt();
                            if (volume <= 5 && volume >= 1) {
                                String whichBook = "Volume " + volume;
                                basket.add(whichBook);
                                System.out.println("added to basket: " + whichBook);
                            } else {
                                System.out.println("Requested volume not recognised. Please try again.");
                            }
                        }

                        break;

                    case "no":
                        System.out.println("Items in basket:");
                        for (String book : basket) {
                            System.out.println(book);}
                            System.out.println();
                        System.out.println("Calculating cost of basket...");
                        running = false;
                        break;

                    default :
                        System.out.println("please type 'yes' or 'no'");
                        break;
                                    }
                                }
                            }
                        }

**Comment by fern-leigh-zz** [comment]
^^ That's the code I'm on about - just in case I add more and break everything by the time you see this issue!

**Comment by timpharo** [comment]
Cool will try and have a look tonight or tomorrow morning on the tram

**Comment by timpharo** [comment]
Just had a look and i can see you have now started writing tests 👍 Looks good and im guessing you got rid of the scanner so that it would be easier to test. Above is a few suggestions.  Ignore the .xml file edits :) https://github.com/Jadelette/Katas/commit/d678231e3b7e876288f2fe49ae281fb913713f75
