### ISSUE TITLE
Issue 2: No 'run' option for tests

### ISSUE THREAD

**Issue by fern-leigh-zz** [Jadelette/Katas#3]
Whyyy? 

![image](https://user-images.githubusercontent.com/35224466/47614974-5629c280-daa0-11e8-9a4b-385e3e7371d5.png)

**Comment by fern-leigh-zz** [comment]
Figured this one out too - pesky pair of missing brackets! 

The test still isn't working though - as it doesn't seem to recognise the array name.

I think I need to go through testing a bit more with you next time I see you! 

Are you free any afternoons next week?

**Comment by fern-leigh-zz** [comment]
Nvm - got it. I need to create the array in the test page. Still not really sure why... but sort of understand that I'm giving it specific criteria. 

Getting there slowly...

**Comment by timpharo** [comment]
Will have a look and see if i can do sometime next week, although it is hectic at work i may be able to find some time... Leave it with me

**Comment by timpharo** [comment]
Ok, just had a look.  Your `potter` seems to be marked as excluded which tells IntelliJ to ignore the code. If you right click go to `Mark directory as` -> `Cancel Exclusion`.

**Comment by fern-leigh-zz** [comment]
Hey - yeah, I've excluded it on purpose at the mo, as I've got ideas for how to solve the problem, but I can't really figure out how to write test for each step (it's pretty convoluted and defo not the best way - but it's all I can think of given what I know how to do in Java). 

I'd like to go through it with you and do it with the tests in our next session - then I can see both ways of doing it. :)
